### ISSUE TITLE
no output at all 

### ISSUE THREAD

**Issue by djmulder** [microknights/Log4NetAdoNetAppender#1]
Hey there, 

I'm running core.net 2.0 and as log4net can't log to the AdoNetAppender I'm using your small module. Now when I make a config error it neatly tells me that it doesn't want to load (eg: if I make the appender type="MicroKnights.Logging.AdoNetAppender", so without the assemblyname it just tells me it doesn't exist). But now nothing, no output at all ,nor does anything show up in the database. 

So I'm not sure anymore where to look/what to debug. Could you check out my (attached) config. to see if there's any error. And help me figure out how to debug this module?

Kind regards,

André

```
<appender name="AdoNetAppender_SqlServer" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender">
    <bufferSize value="1" />
    <connectionType value="System.Data.SqlClient.SqlConnection, System.Data, Version=4.6.25921.2, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" />
    <connectionStringName value="LOGSQLConnectionString" />
    <connectionStringFile value="..\\config.json" />
    <commandText value="INSERT INTO [sftpmanager.log] ([Date],[Thread],[Level],[Logger],[Message],[Exception]) VALUES (@log_date, @thread, @log_level, @logger, @message, @exception)" />
    <commandType value="Text"/>
    <parameter>
      <parameterName value="@log_date" />
      <dbType value="DateTime" />
      <layout type="log4net.Layout.PatternLayout" value="%date{yyyy'-'MM'-'dd HH':'mm':'ss'.'fff}" />
    </parameter>
    <parameter>
      <parameterName value="@thread" />
      <dbType value="String" />
      <size value="255" />
      <layout type="log4net.Layout.PatternLayout" value="%thread" />
    </parameter>
    <parameter>
      <parameterName value="@log_level" />
      <dbType value="String" />
      <size value="50" />
      <layout type="log4net.Layout.PatternLayout" value="%level" />
    </parameter>
    <parameter>
      <parameterName value="@logger" />
      <dbType value="String" />
      <size value="255" />
      <layout type="log4net.Layout.PatternLayout" value="%logger" />
    </parameter>
    <parameter>
      <parameterName value="@message" />
      <dbType value="String" />
      <size value="4000" />
      <layout type="log4net.Layout.PatternLayout" value="%message" />
    </parameter>
  </appender>
```

**Comment by djmulder** [comment]
I found out what the problem was:
- connectionType was wrong.

It never actually made the connection.

**Comment by djmulder** [comment]
Suggested change in your helper:
appender.ConnectionString = connectionString;
appender.ConnectionType = typeof(SqlConnection).AssemblyQualifiedName;
appender.ActivateOptions();

**Comment by microknights** [comment]
What was `appender.ConnectionType` ?

If `ConnectionType` is different than  `SqlConnection` provided by then `SqlClient` nuget, there must be another found within the assembly path? Do you have a mixed setup (.net core and .net Framework)?

**Comment by microknights** [comment]
I will have a look on that property, and its behavior.

It make sense to default to the provided SqlClient.

**Comment by microknights** [comment]
NuGet package `MicroKnights.Log4NetAdoNetAppender -Version 1.0.2` uploaded, and available within minutes/hours

**Comment by microknights** [comment]
Now defaults to provided SqlClient
