### ISSUE TITLE
Target .NET Standard 2.0

### ISSUE THREAD

**Issue by jukkahyv** [microknights/Log4NetAdoNetAppender#10]
This should be fairly simple. You could probably drop some of the references. I can try to do this myself, but first I'd need the strong-naming to be done, so we can start using this library.

**Comment by microknights** [comment]
Yep, i will make a `netstandard2.0` target. I don't think there should be any complications with that.

**Comment by jukkahyv** [comment]
All right, thank you!

**Comment by microknights** [comment]
I have uploaded a new nuget including `netstandard2.0` target.

**Comment by jukkahyv** [comment]
Thank you!
