### ISSUE TITLE
Reading ConnectionStringFile property fails for V2 works in v1.0.2

### ISSUE THREAD

**Issue by BergeAadland** [microknights/Log4NetAdoNetAppender#11]
The following config works in v.1.0.2 and will read connection string from 
appsettings.json: 
>{
>  "ConnectionStrings": {
>        "Log4Net": "data source=.; initial catalog=DB;integrated security=true;"
>      },
>   "APP": {..}
>}

log4net.config:
>     <appender name="AdoNetBusinessAppender" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender">
>      <connectionType value="System.Data.SqlClient.SqlConnection,System.Data,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" />
>      <connectionStringName value="Log4Net" />
>      <connectionStringFile value="appsettings.json" />

In V.2 this results in 
>log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [connectionStringName] to set object on [MicroKnights.Logging.AdoNetAppender]

**Comment by microknights** [comment]
ok, i will take a look at it.

**Comment by microknights** [comment]
I have released a nuget `2.0.1`, can you test it when it is available.
