### ISSUE TITLE
Supported custom layout ?

### ISSUE THREAD

**Issue by sgal008** [microknights/Log4NetAdoNetAppender#12]
I use Custom layout to store my MS database table,but there are some problems
![image](https://user-images.githubusercontent.com/42566429/72048558-0081b480-32f8-11ea-9a96-b6b471feff7b.png)
[DongGuan.Web.Models.MyLayout] is my custom layout type

**Comment by microknights** [comment]
I think the issue is that you must specify the assembly name of your custom layout type.

So try this:
```
<layout type="DongGuan.Web.Models.MyLayout, (write assembly name here)">
   ...
</layout>
```

Else post you config file here....

**Comment by sgal008** [comment]
Thanks, the problem was solved, I started using on log4net yesterday,unskilled in use.
