### ISSUE TITLE
Anyway i can ignore logs when find certain value in my customer property. Does this class support filtering

### ISSUE THREAD

**Issue by KamranShahid** [microknights/Log4NetAdoNetAppender#13]
I have added following in my appender settings

```
   <parameter>
      <parameterName value="_context" />
      <dbType value="String" />
      <size value="25" />
      <layout type="log4net.Layout.RawPropertyLayout">
        <key value="Context" />
      </layout>
    </parameter>

    <filter type="log4net.Filter.PropertyFilter">
      <key value="Context" />
      <stringToMatch value="Transaction" />
      <acceptOnMatch value="false" />
    </filter>
```

What i am doing is logging lot's of scenario. But i wanted to skip logs going to db command when Context Property have value ="Transaction"

But it seems to be not working. 
Please let me know what i need to correct

you can check my related question on stackoverflow

https://stackoverflow.com/questions/59751628/how-to-ignore-logs-when-some-property-have-certain-value-in-log4net

**Comment by microknights** [comment]
I have never used the `Filters`, but that part seems correct. Have you tried the following appender config:

```
   <parameter>
      <parameterName value="_context" />
      <dbType value="String" />
      <size value="25" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%property{Context}" />
      </layout>
    </parameter>
```
That is how i normally do custom fields.

**Comment by KamranShahid** [comment]
Let me try

**Comment by microknights** [comment]
Just for testing, can you try using the `log4net.Filter.StringMatchFilter` and place the `Transaction` text in the Message. That might gives us some clues...

**Comment by microknights** [comment]
I have done some investigation and debugging. First of all, the `Filter` logic is not part of the appenders, at least not for AdoNetAppender, it is a general thing placed in the core of log4net.

And the sad news is, it seems only possible to filter on the predefined fields by log4net - so custom fields not supported. I tried with your `CustomFilter` and `loggingEvent.Properties` is always empty, i expect our custom fields to be placed here.

I can not find any documentation that states whatever this is supported or not.

**Comment by KamranShahid** [comment]
I am using LogicalThreadContext.Properties to add this properties. don't know why it is not there in loggigEvents.Properties but shown in loggingEvent.GetLoggingEventData()

**Comment by KamranShahid** [comment]
> Just for testing, can you try using the `log4net.Filter.StringMatchFilter` and place the `Transaction` text in the Message. That might gives us some clues...

Any idea how should i place it


 ```
<filter type="MyAssembly.CustomFilter, MyAssembly">
      <filter type="log4net.Filter.StringMatchFilter">
        <!--<key value="Context" />-->
        <stringToMatch value="Transaction" />
        <acceptOnMatch value="false" />
      </filter>
    </filter>
    <filter type="log4net.Filter.LevelRangeFilter">
      <acceptOnMatch value="true" />
      <levelMin value="DEBUG" />
      <levelMax value="FATAL" />
    </filter>
or 


or following way

 <filter type="log4net.Filter.LevelRangeFilter">
      <acceptOnMatch value="true" />
      <levelMin value="DEBUG" />
      <levelMax value="FATAL" />
    </filter>
   <filter type="log4net.Filter.StringMatchFilter">
      <stringToMatch value="Transaction" />
      <acceptOnMatch value="false" />
    </filter>
```

**Comment by microknights** [comment]
The solution will be a custom filter, similar to this:

```
    public class CustomFilter : FilterSkeleton
    {
        private readonly IList<IFilter> _filters = new List<IFilter>();
        public override FilterDecision Decide(LoggingEvent loggingEvent)
        {
            if (loggingEvent == null)
                throw new ArgumentNullException(nameof(loggingEvent));

            var properties = loggingEvent.GetProperties();
            if (properties != null && (properties[Key] as string ?? properties[Key]?.ToString()) == StringToMatch )
            {
                return AcceptOnMatch ? FilterDecision.Accept : FilterDecision.Deny;
            }

            if (_filters.All(x => x.Decide(loggingEvent) != FilterDecision.Accept))
            {
                return FilterDecision.Neutral;
            }

            // All conditions are true
            return AcceptOnMatch ? FilterDecision.Accept : FilterDecision.Deny;
        }

        public IFilter Filter
        {
            set => _filters.Add(value);
        }

        public bool AcceptOnMatch { get; set; }

        public string Key { get; set; }
        public string StringToMatch { get; set; }
    }
```

I have also posted this on the SO post.

**Comment by KamranShahid** [comment]
Thanks. let me try

**Comment by microknights** [comment]
With the `CustomFilter` code i listed, it should work with:

```
<filter type="log4net.Filter.LevelRangeFilter">
	<acceptOnMatch value="true" />
	<levelMin value="DEBUG" />
	<levelMax value="FATAL" />
</filter>
<filter type="MyAssembly.CustomFilter, MyAssembly">
	<key value="Context" />
	<stringToMatch value="Transaction" />
	<acceptOnMatch value="false" />
</filter>      
```

I have removed the nesting of the filters. So it goes through the filter chain one by one, and if it passes all filters it should be logged.

**Comment by KamranShahid** [comment]
Not worked

    public class CustomFilter : FilterSkeleton
    {
        private readonly IList<IFilter> _filters = new List<IFilter>();
        public override FilterDecision Decide(LoggingEvent loggingEvent)
        {
            if (loggingEvent == null)
                throw new ArgumentNullException(nameof(loggingEvent));

            var properties = loggingEvent.GetProperties();
            if (Key != null && properties != null && (properties[Key] as string ?? properties[Key]?.ToString()) == StringToMatch)
            {
                return AcceptOnMatch ? FilterDecision.Accept : FilterDecision.Deny;
            }

            if (_filters.All(x => x.Decide(loggingEvent) != FilterDecision.Accept))
            {
                return FilterDecision.Neutral;
            }
            // All conditions are true
            return AcceptOnMatch ? FilterDecision.Accept : FilterDecision.Deny;
        }

        public IFilter Filter
        {
            set => _filters.Add(value);
        }

        public bool AcceptOnMatch { get; set; }

        public string Key { get; set; }
        public string StringToMatch { get; set; }
    }


  <filter type="log4net.Filter.LevelRangeFilter">
      <acceptOnMatch value="true" />
      <levelMin value="DEBUG" />
      <levelMax value="FATAL" />
    </filter>
    <filter type="MyAssembly.CustomFilter, MyAssembly">
      <key value="Context" />
      <stringToMatch value="Transaction" />
      <acceptOnMatch value="false" />
    </filter>

**Comment by microknights** [comment]
If you need someone to help you, you have to provide more detailed information. Also this issue is getting beyond the scope of this project, so maybe it is better to post it on https://stackoverflow.com/

**Comment by KamranShahid** [comment]
Hi Frank,
Pardon to Reopening the issue.
I were able to workout the configuration and it is like

 <filter type="MyClass, My Assembly">
      <key value="TransactionId" />
      <stringToMatch value="" />
      <acceptOnMatch value="false" />
    </filter>
    <filter type="log4net.Filter.LevelRangeFilter">
      <acceptOnMatch value="true" />
      <levelMin value="DEBUG" />
      <levelMax value="FATAL" />
    </filter>

One more question is if i want to put a case like 
TransactionId is null or empty or txnId is null or 0
If that can type of OR statement possible here in filter configuration
