### ISSUE TITLE
Net Core 3.1

### ISSUE THREAD

**Issue by Looooooka** [microknights/Log4NetAdoNetAppender#14]
Same request as for Log4NetHelper.
Any chance this could get updated to the latest net standard to support net core 3.1
I mean I'm sure I can make it work but since I use this in a lot of project I'd prefer to have access to your nuget version :)

**Comment by microknights** [comment]
Yes, i can do that :)

But do you have any support issue now - on net core 3.1 ?

**Comment by Looooooka** [comment]
Well the only issue is appenders using your library don't work under 3.1 so half the logging is dead for me. So it's just a versioning problem. No issues with the code on my end :) 
Like I said I'm pretty sure that making both nugets packages compatible with the new standard would resolve the issue.
I'm currently swamped with a few projects so I thought I'd just ask if these could be updated to avoid needlessly building my own versions.
Other than that I've been more than happy with the libraries until I decided to update from net core 2x to 3.x and noticed the standards library got upped a version as well.

**Comment by microknights** [comment]
I can target the package to netstandard2.1, but that will be for .net core 3.0+. But i don't think that "lifting" the version will help you, it must be something else. Do you have a reproducible example you can test on?
I think it will have something to do with the SqlClient version being used. Do you known which version your running - where it is not working?

**Comment by microknights** [comment]
Also there have been some roadmap changes from Microsoft, moving from `System.Data.SqlClient` to `Microsoft.Data.SqlClient`. I don't know if using both could bring some 
"noise"..

**Comment by microknights** [comment]
okay, you could be right at something. Just did a quick test and i didn't get it to log under `.netstandard2.1` using `System.Data.SqlClient`, whereas it worked with `Micosoft.Data.SqlClient`. Since Microsoft has changed to library, it makes perfect sense to follow that path also.

There will be a version 2.1 shortly, and keep in mind to change the .config and switch to the new `Microsoft.Data.SqlClient`. I will update the Readme.

**Comment by Looooooka** [comment]
Sorry for the late reply. After reading your question about the sqlclient I remembered I too add #IF compiler lines to handle the change to Micosoft.Data.SqlClient.
Completely forgot about it. Changing to that has fixed the problem! 
Thank you for your speedy replies
