### ISSUE TITLE
Is this suppossed to work with OracleConnection?

### ISSUE THREAD

**Issue by sowacx** [microknights/Log4NetAdoNetAppender#15]
Hey,
I am trying to setup yours appender with OracleDB.
In a project I am referencing Oracle.ManagedDataAccess.Core 2.19.70.
So i have setup connectionType as follow:
`    <connectionType value="Oracle.ManagedDataAccess.Client.OracleConnection, 
         Oracle.ManagedDataAccess, Version=2.0.19.1, 
         Culture=neutral, PublicKeyToken=89b483f429c47342" />`
I'am setting connection string at runtime (using call like at Log4NetHelper)
Unfortunatelly after start and logger configuration I'm getting GenericFailure ErrorCode = GenericFailure from appender when running.

Question is do you even support something diefferent than MSSQL?

**Comment by microknights** [comment]
I have never tested it on Oracle, but try take a peek on this (i know it is old, but..) https://stackoverflow.com/questions/43085945/c-sharp-log4net-and-oracle-11g

What .Net Framework / dotnet core - version are you running?

**Comment by sowacx** [comment]
Thanks for response. 
Setting up connection type gives me:
`Could not load file or assembly 'Oracle.ManagedDataAccess, Version=4.121.2.0, Culture=neutral, PublicKeyToken=89b483f429c47342'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)`

I guess that's because I'm using it alongside .NET Core 2.1. I don't if I'm referencing this adapter wrong way or that's just not possible :(

Lately I've been testing also with connection string defined to reduce number of potential problems. Now I will try to clone yours code to get some insights...

**Comment by microknights** [comment]
It says it can not load/find the assembly, so check if; type, name, version and publickeytoken is correct.

**Comment by sowacx** [comment]
Ok, I have it working. It seems that line at constructor:
`ConnectionType = typeof(SqlConnection).AssemblyQualifiedName;`
is spoiling whole thing. 

At my case connection type is being resolved by LazyResolveConnectionType in next steps and I don't even need to switch to something like:
`ConnectionType = typeof(Oracle.ManagedDataAccess.Client.OracleConnection).AssemblyQualifiedName;`
Just commenting out that line is enough at this case.

Just to clear out, im staying with:
`<connectionType value="Oracle.ManagedDataAccess.Client.OracleConnection, 
         Oracle.ManagedDataAccess, Version=2.0.19.1, 
         Culture=neutral, PublicKeyToken=89b483f429c47342" />` at config file

**Comment by microknights** [comment]
I can see your issue, and it is the default initializing - that you overwrite in the configuration later on.

The easy fix could be to have `System.Data.SqlClient` or `Microsoft.Data.SqlClient` package reference (defended on .net standard version) without actually using it.

Meanwhile i will try remove this "hardcoded" dependency, but i need some research time on it. I can provide a "*-beta1" nuget that you can test on - if you are interested?

**Comment by sowacx** [comment]
For now I will use edited code, but I'm surely interested in switching to fixed nuget package. 

I'm looking forward for fixed version I will be able to test it aganst oracle db.

**Comment by microknights** [comment]
Hi @sowacx 

I am about to do the release, do you have a time to test this `MicroKnights.Log4NetAdoNetAppender 2.2.0-alpha2`. The runtime dependency to SqlConnection is removed from the ctor, as you mentioned.

Cheers, Frank
