### ISSUE TITLE
How to override MicroKinghts AdoNetAppender connectionstring from code behind, Not from AppSettings.Json in AspNetCore application

### ISSUE THREAD

**Issue by jsurana** [microknights/Log4NetAdoNetAppender#17]
I want to define MicroKinghts AdoNetAppender connectionstring from code behind. I don't want to define connection string in AppSettings.Json in AspNetCore application

**Comment by microknights** [comment]
Yes, take a look at my other project https://github.com/microknights/Log4NetHelper.

**Comment by jsurana** [comment]
I checked it but didn't understand what needs to be done to define connectionstring at run time from code behind. Can you please provide detailed inputs on this.

**Comment by microknights** [comment]
With Log4NetHelper you do this:
```
AdoNetAppenderHelper.SetConnectionString("this is the actual connection string");
```
It will then find the AdoNetAppender and set the ConnectionString for you.

Ensure that the `AdoNetAppenderHelper.SetConnectionString` call is done right after `log4net.Config.XmlConfigurator.Configure()`.

**Comment by jsurana** [comment]
Thank you. Got it.
