### ISSUE TITLE
MicroKnightsLogging with Dapper instead of Plain ado.net

### ISSUE THREAD

**Issue by KamranShahid** [microknights/Log4NetAdoNetAppender#19]
Can someone help me in creating a Dapper version of MicroKnightsLogging which i want to use in .net core 3.1 application with Mysql 8.0
Like to take advantage of some async and other features in dapper

**Comment by microknights** [comment]
I think `async` will require a lot of rewrite, and not only in `AdoNetAppender` but also in the core of `log4net` to make it fully `async`.

But i can not seen any advantage of using Dapper, with the exception of making the development easier. The `AdoNetAppender` is using native sql prepared statements - the same way as Dapper works.

**Comment by KamranShahid** [comment]
i am talking about dapper executeasync
