### ISSUE TITLE
format of connectionstring file 

### ISSUE THREAD

**Issue by bpetersen1** [microknights/Log4NetAdoNetAppender#2]
Hi, does the connectionstring file look for keys within a Connection string section eg.

  "ConnectionStrings": {
"log4net" : " [The connection string]"
}

or is it just a flat file 

{
"log4net" : "[The Connection string]"
}

I'm currently reading from my appsettings.json file, is this ok or should i create a separate file ?

**Comment by microknights** [comment]
This is the way:

```
"connectionStrings": {
"log4net" : " [The connection string]"
}
```
where as the name `log4net` is set on the `ConnectionStringName` property in your log4net.config

**Comment by bpetersen1** [comment]
Thanks, 

And is it ok reading from the appsettings.json file, or do i have to create a seperate file with connection strings

**Comment by microknights** [comment]
Yes, you can specify `appsettings.json`. The only requirement for the *.json file is a `"connectionStrings"` section that contains the `ConnectionStringName`.

**Comment by bpetersen1** [comment]
Thanks,
