### ISSUE TITLE
Error While making SQL Connection

### ISSUE THREAD

**Issue by amit141189** [microknights/Log4NetAdoNetAppender#21]
log4net:ERROR [AdoNetAppender] ErrorCode: GenericFailure. Failed to load connection type [System.Data.SqlClient.SqlConnection,System.Data.SqlClient,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089]
System.IO.FileNotFoundException: Could not load file or assembly 'System.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

**Comment by amit141189** [comment]
log4net:ERROR [AdoNetAppender] ErrorCode: GenericFailure. Failed to load connection type [Microsoft.Data.SqlClient.SqlConnection,Microsoft.Data.SqlClient,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089]
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Data.SqlClient, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. The system cannot find the file specified.

**Comment by microknights** [comment]
What .net core version are you running?

`Microsoft.Data.SqlClient` latest version is only `<PackageReference Include="Microsoft.Data.SqlClient" Version="2.0.0" />`

**Comment by shorbachuk** [comment]
I also cannot get this working. I have:
<PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AspNetCoreHostingModel>inprocess</AspNetCoreHostingModel>
  </PropertyGroup>

When I revert to "MicroKnights.Log4NetAdoNetAppender" Version="2.0.1" it works fine.

**Comment by microknights** [comment]
I would like to help, but need a little more info - so i can reproduce the problem. Can you post your  log4net configuration?

**Comment by microknights** [comment]
@shorbachuk   I would like to help, but need a little more info so i can reproduce the problem. Can you post your log4net configuration?

**Comment by shorbachuk** [comment]
`<?xml version="1.0" encoding="utf-8"?>
<log4net>
  <root>
    <level value="DEBUG" />
    <appender-ref ref="RollingFileAppender" />
    <appender-ref ref="AdoNetAppender" />
  </root>
  <appender name="RollingFileAppender" type="log4net.Appender.RollingFileAppender">
    <file value="..\\Logs\\App.log" />
    <appendToFile value="true" />
    <rollingStyle value="Size" />
    <maxSizeRollBackups value="5" />
    <maximumFileSize value="5MB" />
    <staticLogFileName value="true" />
    <layout type="log4net.Layout.PatternLayout">
      <conversionPattern value="%d|%-5p|%property{log4net:HostName}|%t|%c|%property{activity_id}|%property{user}|%m%n" />
    </layout>
  </appender>
  <appender name="AdoNetAppender" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender">>
    <bufferSize value="1" />
    <reconnectonerror value="true" />
    <connectionType value="Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient, Version=1.0.0.0,Culture=neutral,PublicKeyToken=23ec7fc2d6eaa4a5"/>
    
    <connectionString value="" />
    <commandText value="INSERT INTO Logs ([Date],[User],[ActivityId],[Thread],[Level],[Logger],[Message],[Exception],[HostName]) VALUES (@log_date, @user, @activity_id, @thread, @log_level, @logger, @message, @exception, @hostname)" />
    <parameter>
      <parameterName value="@log_date" />
      <dbType value="DateTime" />
      <layout type="log4net.Layout.RawTimeStampLayout" />
    </parameter>
    <parameter>
      <parameterName value="@user" />
      <dbType value="String" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%property{user}" />
      </layout>
    </parameter>
    <parameter>
      <parameterName value="@activity_id" />
      <dbType value="String" />
      <size value="36" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%property{activity_id}" />
      </layout>
    </parameter>
    <parameter>
      <parameterName value="@thread" />
      <dbType value="String" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%thread" />
      </layout>
    </parameter>
    <parameter>
      <parameterName value="@log_level" />
      <dbType value="String" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%level" />
      </layout>
    </parameter>
    <parameter>
      <parameterName value="@logger" />
      <dbType value="String" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%logger" />
      </layout>
    </parameter>
    <parameter>
      <parameterName value="@message" />
      <dbType value="String" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%message" />
      </layout>
    </parameter>
    <parameter>
      <parameterName value="@exception" />
      <dbType value="String" />
      <layout type="log4net.Layout.ExceptionLayout" />
    </parameter>
    <parameter name="@hostname">
      <parameterName value="@hostname" />
      <dbType value="String" />
      <layout type="log4net.Layout.PatternLayout" value="%property{log4net:HostName}" />
    </parameter>
  </appender>
  <logger additivity="false" name="Hangfire">
    <level value="INFO" />
  </logger>
</log4net>`

**Comment by microknights** [comment]
@shorbachuk  I have fixed the format, but is it a direct copy? The is a xml tag error on the end of tag `<appender name="AdoNetAppender"` ?

But since the exception is related on the SqlClient to will try reproduce the error. What NuGet version of `Microsoft.Data.SqlClient.SqlConnection` do you use in you project?

**Comment by shorbachuk** [comment]
I dug into this a little more, and I dont think its related to loading the assembly. It seems I had omitted "<size value="xxx" />" on some of my parameters (shown above). My guess is `System.Data.SqlClient` did not care about this, whereas `Microsoft.Data.SqlClient.SqlConnection` now does.

**Comment by microknights** [comment]
I have tried your configuration, without any errors shown. Do you get an exception or any other error indication?

You can try this, before you initialize log4net:
```
                InternalDebugHelper.EnableInternalDebug((source,args) =>
                {
                    var header = string.Join(" ",args.LogLog.TimeStamp,args.LogLog.Prefix);
                    if (args.LogLog.Exception != null)
                    {
                        Console.WriteLine($"{header} ERROR {args.LogLog.Exception.Message}");
                        Console.WriteLine(args.LogLog.Exception.StackTrace);
                    }
                    else
                    {
                        Console.WriteLine($"{header} INFO {args.LogLog.Message}");
                    }
                });
```
_with my `MicroKnights.Log4NetHelper` NuGet_

It should print out a lot of information of what log4net i doing.

**Comment by shorbachuk** [comment]
As I mentioned, its actually not an error loading the assembly as I originally thought. I get this exception:
```
log4net:ERROR [AdoNetAppender] ErrorCode: GenericFailure. Exception while writing to database
System.InvalidOperationException: SqlCommand.Prepare method requires all variable length parameters to have an explicitly set non-zero Size.
   at Microsoft.Data.SqlClient.SqlParameter.Prepare(SqlCommand cmd)
   at Microsoft.Data.SqlClient.SqlCommand.Prepare()
   at MicroKnights.Logging.AdoNetAppender.SendBuffer(IDbTransaction dbTran, LoggingEvent[] events)
   at MicroKnights.Logging.AdoNetAppender.SendBuffer(LoggingEvent[] events)
```

**Comment by microknights** [comment]
a bit odd i don't get that error, when running with you configuration.

But all parameters of type `<dbType value="String" />` must also have a `<size value="n" />` set. Take a look on https://github.com/microknights/Log4NetAdoNetAppender.

**Comment by fernandoreis9173** [comment]
ola bom dia , eu tenho essa configuração no log4net.config, estou tentando salvar meus loggs no banco de dados, que ja esta criado. 




<?xml version="1.0" encoding="utf-8" ?>
  <log4net>
  <root>
    <level value="All" />
    <appender-ref ref="AdoNetAppender" />
  </root>

 <appender name="AdoNetAppender" type="log4net.Appender.ConsoleAppender">
    <layout type="log4net.Layout.PatternLayout">
    <bufferSize value="100" />
      </layout>
    <connectionType value="System.Data.SqlClient.SqlConnection, System.Data, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <connectionString value="data Server=MNSNTE01;Database=t_NCM;user id=t_NCM_app;password=2L1_$$#u33MW_Wi##b$_w;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=false;Integrated Security=false;Trusted_Connection=true;Connection Timeout=30]" />
    <commandText value="INSERT INTO Log ([Date],[Thread],[Level],[Logger],[Message],[Exception]) VALUES (@log_date, @thread, @log_level, @logger, @message, @exception)" />
    <parameter>
        <parameterName value="@log_date" />
        <dbType value="DateTime" />
        <layout type="log4net.Layout.RawTimeStampLayout" />
    </parameter>
    <parameter>
        <parameterName value="@thread" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%thread" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@log_level" />
        <dbType value="String" />
        <size value="50" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%level" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@logger" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%logger" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@message" />
        <dbType value="String" />
        <size value="4000" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%message" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@exception" />
        <dbType value="String" />
        <size value="2000" />
        <layout type="log4net.Layout.ExceptionLayout" />
    </parameter>
</appender>


</log4net>


porem o erro que mostra no console é esse

log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [bufferSize] to set object on [log4net.Layout.PatternLayout]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [connectionType] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [connectionString] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [commandText] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [parameter] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [parameter] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [parameter] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [parameter] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [parameter] to set object on [log4net.Appender.ConsoleAppender]
log4net:ERROR XmlHierarchyConfigurator: Cannot find Property [parameter] to set object on [log4net.Appender.ConsoleAppender]
You is crazy cachoeira doido!
You is crazy cachoeira doido!
You is crazy cachoeira doido!


esse comentario "You is crazy cachoeira doido!" eu faço em program. cs com 
log.Error("You is crazy cachoeira doido!");
        log.Warn("You is crazy cachoeira doido!");
        log.Info("You is crazy cachoeira doido!");


consegue me ajudar?

**Comment by fernandoreis9173** [comment]
<?xml version="1.0" encoding="utf-8" ?>
  <log4net>
  <root>
    <level value="All" />
    <appender-ref ref="AdoNetAppender" />
  </root>

 <appender name="AdoNetAppender" type="log4net.Appender.ConsoleAppender">
    <layout type="log4net.Layout.PatternLayout">
    <bufferSize value="100" />
      </layout>
    <connectionType value="System.Data.SqlClient.SqlConnection, System.Data, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <connectionString value="data Server=MNSNTE01;Database=t_NCM;user id=t_NCM_app;password=2L1_$$#u33MW_Wi##b$_w;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=false;Integrated Security=false;Trusted_Connection=true;Connection Timeout=30]" />
    <commandText value="INSERT INTO Log ([Date],[Thread],[Level],[Logger],[Message],[Exception]) VALUES (@log_date, @thread, @log_level, @logger, @message, @exception)" />
    <parameter>
        <parameterName value="@log_date" />
        <dbType value="DateTime" />
        <layout type="log4net.Layout.RawTimeStampLayout" />
    </parameter>
    <parameter>
        <parameterName value="@thread" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%thread" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@log_level" />
        <dbType value="String" />
        <size value="50" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%level" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@logger" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%logger" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@message" />
        <dbType value="String" />
        <size value="4000" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%message" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@exception" />
        <dbType value="String" />
        <size value="2000" />
        <layout type="log4net.Layout.ExceptionLayout" />
    </parameter>
</appender>


</log4net>

**Comment by fernandoreis9173** [comment]
`<?xml version="1.0" encoding="utf-8" ?>
  <log4net>
  <root>
    <level value="All" />
    <appender-ref ref="AdoNetAppender" />
  </root>

 <appender name="AdoNetAppender" type="log4net.Appender.ConsoleAppender">
    <layout type="log4net.Layout.PatternLayout">
    <bufferSize value="100" />
      </layout>
    <connectionType value="System.Data.SqlClient.SqlConnection, System.Data, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <connectionString value="data Server=MNSNTE01;Database=t_NCM;user id=t_NCM_app;password=2L1_$$#u33MW_Wi##b$_w;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=false;Integrated Security=false;Trusted_Connection=true;Connection Timeout=30]" />
    <commandText value="INSERT INTO Log ([Date],[Thread],[Level],[Logger],[Message],[Exception]) VALUES (@log_date, @thread, @log_level, @logger, @message, @exception)" />
    <parameter>
        <parameterName value="@log_date" />
        <dbType value="DateTime" />
        <layout type="log4net.Layout.RawTimeStampLayout" />
    </parameter>
    <parameter>
        <parameterName value="@thread" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%thread" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@log_level" />
        <dbType value="String" />
        <size value="50" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%level" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@logger" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%logger" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@message" />
        <dbType value="String" />
        <size value="4000" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%message" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@exception" />
        <dbType value="String" />
        <size value="2000" />
        <layout type="log4net.Layout.ExceptionLayout" />
    </parameter>
</appender>


</log4net>`

**Comment by fernandoreis9173** [comment]
`
  <log4net>
  <root>
    <level value="All" />
    <appender-ref ref="AdoNetAppender" />
  </root>

 <appender name="AdoNetAppender" type="log4net.Appender.ConsoleAppender">
    <layout type="log4net.Layout.PatternLayout">
    <bufferSize value="100" />
      </layout>
    <connectionType value="System.Data.SqlClient.SqlConnection, System.Data, Version=1.0.3300.0, Culture=neutral, PublicKeyToken=b77a5c561934e089" />
    <connectionString value="data Server=MNSNTE01;Database=t_NCM;user id=t_NCM_app;password=2L1_$$#u33MW_Wi##b$_w;MultipleActiveResultSets=true;Encrypt=False;TrustServerCertificate=false;Integrated Security=false;Trusted_Connection=true;Connection Timeout=30]" />
    <commandText value="INSERT INTO Log ([Date],[Thread],[Level],[Logger],[Message],[Exception]) VALUES (@log_date, @thread, @log_level, @logger, @message, @exception)" />
    <parameter>
        <parameterName value="@log_date" />
        <dbType value="DateTime" />
        <layout type="log4net.Layout.RawTimeStampLayout" />
    </parameter>
    <parameter>
        <parameterName value="@thread" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%thread" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@log_level" />
        <dbType value="String" />
        <size value="50" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%level" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@logger" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%logger" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@message" />
        <dbType value="String" />
        <size value="4000" />
        <layout type="log4net.Layout.PatternLayout">
            <conversionPattern value="%message" />
        </layout>
    </parameter>
    <parameter>
        <parameterName value="@exception" />
        <dbType value="String" />
        <size value="2000" />
        <layout type="log4net.Layout.ExceptionLayout" />
    </parameter>
</appender>


</log4net>`

**Comment by fernandoreis9173** [comment]
[log4net.txt](https://github.com/microknights/Log4NetAdoNetAppender/files/11789455/log4net.txt)

**Comment by microknights** [comment]
@fernandoreis9173 please write in english :) 

Also create an new issue (this one is closed), and if you post the config files remember to remove any username/passwords.

**Comment by Ledragon** [comment]
Future note for me: `size` is also required for datetime2
