### ISSUE TITLE
Is SQLite supported ?

### ISSUE THREAD

**Issue by WarBorg** [microknights/Log4NetAdoNetAppender#23]
Hello,

I am trying to setup your appender with a SQLite database.
I have a simple console project created with .NET Core 3.1 with a reference to the Microsoft.EntityFrameworkCore.Sqlite 3.1.8 nuget package.
The configuration file most important rows are as follow:
```
<appender name="AdoNetAppender" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender">
    <bufferSize value="100" />
    <connectionType value="Microsoft.Data.Sqlite.SqliteConnection, Microsoft.EntityFrameworkCore.Sqlite, Version=3.1.8.0, Culture=neutral, PublicKeyToken=adb9793829ddae60" />
    <connectionString value="sqlite" />
    <connectionStringFile value="connectionstrings.json" />
...
```
and the connectionstrings.json contents:
```
{
  "connectionstrings": {
    "sqlite": "Data Source=log4net.db;Version=3;",
  }
}
```
I already have a log4net.db database file with the correct table in it but I am not sure where to place it exactly in the folder structure (I placed it in the same location as log4net.config), also looking at the documentation you provided I see I need a ConnectionStringFile property and the actual json file. Looking at your tests examples I did not see a SQLite example so I just improvised and also I have the same question: where should it be located ? In the same location as the log4net.config ? or in the bin/Debug/bla/bla folder ? (in my tests it is placed in the same location as log4net.config)
Also all files are marked as Always Copy

PS Funny thing is I am not getting any errors or at least I didn't see any... but the table in db file does not get updated

Any help would be appreciated,

Thank you in advance

**Comment by microknights** [comment]
SQLite is listed as supported from the original library, but i have never tested it.

Can you post your full configuration, and i will do some testing the next could of days :)

**Comment by WarBorg** [comment]
I did even better, created the project on github, maybe it will help others:

https://github.com/WarBorg/DotNetCoreLog4NetApplication/tree/main/DotNetCoreLog4NetApplication.Console

**Comment by microknights** [comment]
So is it working now or?

**Comment by WarBorg** [comment]
@microknights nope, same having the problem that the DB is not updated but don't really know how to debug it because I see no errors

**Comment by microknights** [comment]
ok, i will take a look at your project and post if i find anything.

**Comment by WarBorg** [comment]
thank you, maybe you can make a PR on that repo if you manage it to make it work

**Comment by microknights** [comment]
A PR is ready, only a few fixes in the configuration :)

**Comment by WarBorg** [comment]
hello,

thank you, saw the PR, merged it, but still not working :( database is still empty (PS I am using a Mac for development with VS for Mac 2019) don't know if that is of any relevance 

<img width="473" alt="Screenshot 2020-10-17 at 01 06 32" src="https://user-images.githubusercontent.com/7552384/96312822-12c21900-1015-11eb-94a3-9acef8df807f.png">

also check the DB with "DB Browser for SQLite" just to be sure, was still empty

**Comment by microknights** [comment]
I have made a PR and an Issue on you repo, lets continue on that issue...

https://github.com/WarBorg/DotNetCoreLog4NetApplication/issues/3

**Comment by WarBorg** [comment]
will do, should I close this issue ?

**Comment by microknights** [comment]
no, if will close it with a final statement on this issue

**Comment by microknights** [comment]
So, only configuration issues.

And there is a *nix platform error from `Log4Net` v2.0.10+ (up to currenty v2.0.11). So if you use `log4net` v2.0.9 to avoid this.
