### ISSUE TITLE
.Net Core 5.0 version log4net file in sqlserver code not working

### ISSUE THREAD

**Issue by vmutlu** [microknights/Log4NetAdoNetAppender#27]
Hello,
My code in the log4net file in my .Net Core 5.0 project is as follows. I cannot log into the database, although I have applied all what I have written. What can I do ?

<appender name="DatabaseLogger" type="MicroKnights.Logging.AdoNetAppender,  MicroKnights.Log4NetAdoNetAppender">
		<bufferSize value="1" />
		<connectionType value="Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" />
		<connectionString value="myConnectionString" />
		<commandText value="INSERT INTO Logs (Detail,Date,Audit) VALUES (@logDetail,@log_date,@audit)" />
		<parameter>
			<parameterName value="@logDetail" />
			<dbType value="String" />
			<size value="4000" />
			<layout type="Core.CrossCuttingConcerns.Logging.Log4Net.Layouts.JsonLayout, Core" />
		</parameter>
		<parameter>
			<parameterName value="@log_date" />
			<dbType value="DateTime" />
			<layout type="log4net.Layout.PatternLayout" value="%date{dd'-'MM'-'yyyy HH':'mm':'ss'.'fff}" />
		</parameter>
		<parameter>
			<parameterName value="@audit" />
			<dbType value="String" />
			<size value="50" />
			<layout type="log4net.Layout.PatternLayout" value="%level" />
		</parameter>
	</appender>

	<logger name="DatabaseLogger">
		<level value="ALL"></level>
		<appender-ref ref="DatabaseLogger"/>
	</logger>

**Comment by microknights** [comment]
Can you show your entire configuration, without displaying the context (username/password) of the connctionstring?

You could also try the [Log4NetHelper](https://github.com/microknights/Log4NetHelper) project with internal debugging, that could give you come clues.

**Comment by vmutlu** [comment]
@microknights log4net file containing the connection string ->

<log4net>
<appender name="DatabaseLogger" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender">
		<bufferSize value="1" />
		<connectionType value="Microsoft.Data.SqlClient.SqlConnection, Microsoft.Data.SqlClient,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" />
		<connectionString value="Server=DESKTOP-KB74JGP\\SQLEXPRESS;Database=ExampleDB;Integrated Security=true;" />
		<commandText value="INSERT INTO Logs (Detail,Date,Audit) VALUES (@logDetail,@log_date,@audit)" />
		<parameter>
			<parameterName value="@logDetail" />
			<dbType value="String" />
			<size value="4000" />
			<layout type="Core.CrossCuttingConcerns.Logging.Log4Net.Layouts.JsonLayout, Core" />
		</parameter>
		<parameter>
			<parameterName value="@log_date" />
			<dbType value="DateTime" />
			<layout type="log4net.Layout.PatternLayout" value="%date{dd'-'MM'-'yyyy HH':'mm':'ss'.'fff}" />
		</parameter>
		<parameter>
			<parameterName value="@audit" />
			<dbType value="String" />
			<size value="50" />
			<layout type="log4net.Layout.PatternLayout" value="%level" />
		</parameter>
	</appender>

	<logger name="DatabaseLogger">
		<level value="ALL"></level>
		<appender-ref ref="DatabaseLogger"/>
	</logger>
</log4net>

**Comment by microknights** [comment]
hhmm, you configuration should look somehow similar to [log4net.config](https://github.com/microknights/Log4NetAdoNetAppender).

It will never work, if you only have shat you have listed above?

Please read this: [Apache log4net™ Config Examples](https://logging.apache.org/log4net/release/config-examples.html)
