### ISSUE TITLE
Logging get stop after getting  Unable to write data to the transport connection: Broken pipe.

### ISSUE THREAD

**Issue by KamranShahid** [microknights/Log4NetAdoNetAppender#28]
I have a mysql8 db with .net core 3.1 application where logging is taking place.
Problem is logging get stopped when i get above exception. I am using Mysql connector 8.0.25
Strange thing is you look like handled this case via 
```
if (ReconnectOnError && (Connection == null || Connection.State != ConnectionState.Open))
            {
                LogLog.Debug(declaringType, "Attempting to reconnect to database. Current Connection State: " + ((Connection == null) ? SystemInfo.NullText : Connection.State.ToString()));

                InitializeDatabaseConnection();
            }
```

But still logging didn't take place. I have checked the ReconnectOnError property and it is true. now putting log to check connection state when i got this error.
What can i do to resolve this

**Comment by KamranShahid** [comment]
At the moment putting following workaround for such case.

```
try
                {
                    SendBuffer(dbTran, events);
                }
                catch (Exception ex)
                {                 
                    if (Connection != null)
                    {
                        Console.WriteLine($"Connection State: {Connection.State} , ExceptionType:{ex.GetType()}, Exception while logging {ex.Message} ");
                        if (ex.Message != null && ex.Message.ToLower().Contains("unable to write data to the transport connection: broken pipe.") && Connection.State == ConnectionState.Open)
                        {
                            Connection = null;
                        }
                    }
                    throw;
                }
```

**Comment by microknights** [comment]
can you provide the full stacktrace of that exception?

**Comment by KamranShahid** [comment]
> can you provide the full stacktrace of that exception?
My application is running as systemd service. I have enabled buffering in it. (though at the moment set it to 1)
What's the easiest way of getting the stack trace other then console log? reproducing's the error is too hard and i generally waiting for the thing to reproduce.
In log what I see is after getting that exception Connection.State is still open. May be it's a bug in mysql connector itself as thing is even reproducing in mysql 5.6 version

**Comment by KamranShahid** [comment]
I have updated my code to

```
try
                {
                    SendBuffer(dbTran, events);//both calling
                }
                catch (Exception ex)
                {
                    if (Connection != null)
                    {
                        Console.WriteLine($"Connection State: {Connection.State} , ExceptionType:{ex.GetType()}");
                        Console.WriteLine($"Exception while logging:[{ex.Message}]");
                        if (Connection.State == ConnectionState.Open && ex.Message != null && ex.Message.ToLower().Contains("broken pipe"))
                        {
                            Connection = null;
                            Console.WriteLine($"Connection is set as null");
                        }
                    }
                    throw;
                }
```

And waiting for reproducing the error.
Checking logs via following command in linux

`sudo journalctl SYSLOG_IDENTIFIER=MyAppLog --since='-12h'`

**Comment by KamranShahid** [comment]
Last mentioned workaround did worked.

**Comment by KamranShahid** [comment]
strange behavior is on one of the environment it doesn't work.
what is seen is disposeConnection called from tow different threads same time
@microknights how to view log content from
LogLog.Warn(declaringType, "Exception while disposing cached connection object", ex);

**Comment by microknights** [comment]
The `LogLog.Warn(declaringType, "Exception while disposing cached connection object", ex);` will be part of you log4net configuration. Since the database is disconected, it will properly only appear in a ConsoleAppender - if you have one configured?

The `InitializeDatabaseConnection` is not thread-safe, so multiple calls to `DiposeConnection` can easily happens in fail scenarios.

**Comment by KamranShahid** [comment]
> The `LogLog.Warn(declaringType, "Exception while disposing cached connection object", ex);` will be part of you log4net configuration. Since the database is disconected, it will properly only appear in a ConsoleAppender - if you have one configured?
> 
> The `InitializeDatabaseConnection` is not thread-safe, so multiple calls to `DiposeConnection` can easily happens in fail scenarios.

Let me try one possible tweak

```
 private void DiposeConnection(bool isduetodisconnectivity = false)
        {
            if(isduetodisconnectivity)
            {
                lock (Connection)
                {
                    if (Connection != null)
                    {
                        try
                        {
                            Connection.Close();
                        }
                        catch (Exception ex)
                        {
                            LogLog.Warn(declaringType, "Exception while disposing cached connection object", ex);
                            Console.WriteLine($"Exception while disposing cached connection object", ex.Message);
                        }
                        Connection = null;
                    }
                }
            }
            else
            {
                if (Connection != null)
                {
                    try
                    {
                        Connection.Close();
                    }
                    catch (Exception ex)
                    {
                        LogLog.Warn(declaringType, "Exception while disposing cached connection object", ex);
                        Console.WriteLine($"Exception while disposing cached connection object", ex.Message);
                    }
                    Connection = null;
                }
            }
          
        }

```
i will pass isduetodisconnectivity  true after identifying the connection is lost due to broken pipe/reading from the stream has failed

 try
                {
                    SendBuffer(dbTran, events);
                }
                catch (Exception ex)
                {
                    bool dothrow = true;
                    if (Connection != null)
                    {
                        Console.WriteLine($"Connection State: {Connection.State} , ExceptionType:{ex.GetType()}");
                        Console.WriteLine($"Exception while logging:[{ex.Message}]");
                        if (Connection.State == ConnectionState.Open && ex.Message != null
                            && (ex.Message.ToLower().Contains("broken pipe")
                           || ex.Message.ToLower().Contains("reading from the stream has failed.")
                            ))
                        {
                            DiposeConnection(true);
                            Console.WriteLine($"DiposeConnection called");
                            dothrow = false;
                        }
                    }
                    if (dothrow)
                    {
                        throw;
                    }
                }

**Comment by KamranShahid** [comment]
@microknights shouldn't this dispose connection call should be thread safe. i have multiple db appender and might be same case appearing

**Comment by KamranShahid** [comment]
locking Connection object seem did the trick. Thanks

**Comment by KamranShahid** [comment]
[micronight.zip](https://github.com/microknights/Log4NetAdoNetAppender/files/6781824/micronight.zip)

My implementation file locally
