### ISSUE TITLE
Azure ConnectionString

### ISSUE THREAD

**Issue by antonioseric** [microknights/Log4NetAdoNetAppender#30]
I have connectionstring define in variable in Azure app service, I try to use ConnectionStringName without and with file but seams it is not working. 

How to use that connectionstring?

I saw in source code maybe it is missing to Add Environment Variables in config builder `new ConfigurationBuilder().AddEnvironmentVariables()`

**Comment by microknights** [comment]
Hi,

Just to clarify, you have tried using a appsettings.json file with reference of `ConnectionStringName` and it didn't work?

**Comment by antonioseric** [comment]
Yes I try it. It uses connection string from appsettings.json file, which is dev conn string, not from Azure Environment variables (in app it is overwritten with Azure variable connection string)

**Comment by microknights** [comment]
So you don't have a connectionstring file when running in Azure? I am a bit confused about you setup(s).

**Comment by antonioseric** [comment]
I have appsettings.json in project which contains connection string `MoneyFlowDbConnection` for localhost. that case is workig. 

When i deploy app to azure i don't change connectionstring in appsettings.json file. I just add new connection string to configuration of Azure App service.  
![image](https://user-images.githubusercontent.com/4761328/130651888-860486f9-d8ed-44e4-ad92-30b48c19ef09.png)

So my app uses that connection string from azure configuration, but log4net is using configuration from file. log4net can't use configuration for connection string from environment. that is why it has to be added `AddEnvironmentVariables()`. 

I can create PR to fix that if you like....

**Comment by microknights** [comment]
See my comment on the PM https://github.com/microknights/Log4NetAdoNetAppender/pull/31
