### ISSUE TITLE
When the connection string is specified in the user secrets, Log4NetAdoNetAppender fails get the connection string

### ISSUE THREAD

**Issue by boggye** [microknights/Log4NetAdoNetAppender#41]
To reproduce add the connection string to the user secrets file. In VS 2022 one can use the Manage User Secrets. See this for more information: https://learn.microsoft.com/en-us/aspnet/core/security/app-secrets?view=aspnetcore-7.0&tabs=windows.

Once the connection string is added to the user secrets file, enable debug=true for log4net and run the app.

I get this in the debug output:
`log4net:ERROR [AdoNetAppender] ErrorCode: GenericFailure. Could not open database connection []. Connection string context [ConnectionStringFile: ...`

The config I am using:

```xml
<?xml version="1.0" encoding="utf-8"?>
<configuration>
  <log4net debug="true">
    <appender name="AdoNetAppender" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender" > <!-- type="log4net.Appender.AdoNetAppender" --> 
      <bufferSize value="1" />
      <connectionType
        value="System.Data.SqlClient.SqlConnection, System.Data" /> <!-- -->
      <connectionStringName value="mydb" />
      <connectionStringFile value="appsettings.json" />
      <commandText
        value="INSERT INTO log4net.Log ([Date],[Thread],[Level],[Logger],[Message],[Exception]) VALUES (@log_date, @thread, @log_level, @logger, @message, @exception)" />
      <parameter>
        <parameterName value="@log_date" />
        <dbType value="DateTime" />
        <layout type="log4net.Layout.RawTimeStampLayout" />
      </parameter>
      <parameter>
        <parameterName value="@thread" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
          <conversionPattern value="%thread" />
        </layout>
      </parameter>
      <parameter>
        <parameterName value="@log_level" />
        <dbType value="String" />
        <size value="50" />
        <layout type="log4net.Layout.PatternLayout">
          <conversionPattern value="%level" />
        </layout>
      </parameter>
      <parameter>
        <parameterName value="@logger" />
        <dbType value="String" />
        <size value="255" />
        <layout type="log4net.Layout.PatternLayout">
          <conversionPattern value="%logger" />
        </layout>
      </parameter>
      <parameter>
        <parameterName value="@message" />
        <dbType value="String" />
        <size value="-1" />
        <layout type="log4net.Layout.PatternLayout">
          <conversionPattern value="%message" />
        </layout>
      </parameter>
      <parameter>
        <parameterName value="@exception" />
        <dbType value="String" />
        <size value="-1" />
        <layout type="log4net.Layout.ExceptionLayout" />
      </parameter>
    </appender>    
    <appender name="console" type="log4net.Appender.ManagedColoredConsoleAppender">
      <mapping>
        <level value="INFO" />
        <forecolor value="Green" />
      </mapping>
      <mapping>
        <level value="WARN" />
        <forecolor value="Yellow" />
      </mapping>
      <mapping>
        <level value="ERROR" />
        <forecolor value="Red" />
      </mapping>
      <mapping>
        <level value="DEBUG" />
        <forecolor value="Blue" />
      </mapping>
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date %level %logger.%method[%line] - %message%newline" />
      </layout>
    </appender>
    <appender name="file" type="log4net.Appender.RollingFileAppender">
      <file value="main.log" />
      <appendToFile value="true" />
      <rollingStyle value="Size" />
      <maxSizeRollBackups value="5" />
      <maximumFileSize value="25MB" />
      <staticLogFileName value="true" />
      <layout type="log4net.Layout.PatternLayout">
        <conversionPattern value="%date [%thread] %level %logger.%method[%line] - %message%newline" />
      </layout>
    </appender>    
    <root>
      <level value="ALL" />
      <appender-ref ref="AdoNetAppender" />
      <appender-ref ref="console" />
      <appender-ref ref="file" />

    </root>
  </log4net>
</configuration>
```
This call returns the proper connection value: `configuration.GetConnectionString("mydb");` at runtime even when the string is in the user secrets.

User secrets file content:
```json
{
  "ConnectionStrings": {
    "mydb": "Server='<server>'; Database='mydb'; UID='<user>'; PWD='<pwd>';TrustServerCertificate=true"
  }
}
```
(I replaced the real values with place holders)

I also tried it without the `<connectionStringFile value="appsettings.json" />` line hoping the library just uses the default configuration but it doesn't work.

**Comment by microknights** [comment]
Yes, that is a problem. The `Log4NetAdoNetAppender` has no access to the `IConfiguration` of the application, and must do the load itself.
So loading from Secrets is a bit out of scope for this project, but there is another solution :) 
Take a look at my [Log4NetHelper](https://github.com/microknights/Log4NetHelper) project. With that you can set the connection string manually, after you have read all the configuration.

**Comment by boggye** [comment]
Thank you. I added AdoNetAppenderHelper to one of my shared projects and I ended up using `AdoNetAppenderHelper.SetConnectionString(...)`, and it works. 

Not sure what to suggest. In my mind I thought the library somehow uses the configuration api which should be aware of the user secrets, but obviously this is incorrect. Another way would be to have an XmlConfigurator.Configure overload where I can also pass the IConfiguration object, but I haven't looked in detail. For now, this works and I am happy.  

Let me know if you want to keep this open and think more about it. Otherwise, I will close it.

**Comment by boggye** [comment]
Hi,

Thank you! As per your suggestion, I got it working using this sequence:

```
XmlConfigurator.Configure(new FileInfo("log4net.config"));
AdoNetAppenderHelper.SetConnectionString(...);
```

I can close this issue, if you want and there is nothing else to add.

PS. I deleted the previous message because I sent it too early due to a mistake I made.

**Comment by microknights** [comment]
You can close this issue, and i will do some thoughts on the `XmlConfigurator.Configure(config)` :)
