### ISSUE TITLE
System.TypeLoadException:

### ISSUE THREAD

**Issue by gy09535** [microknights/Log4NetAdoNetAppender#6]
I find  this issue " Method 'getProperties' in type 'Microsoft.Extensions.Configuration.ConfigurationBuilder' from assembly 'Microsoft.Extensions.Configuration, Version=1.1.2.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' does not have an implementation. at MicroKnights.Logging.AdoNetAppender.ResolveConnectionString(String& connectionStringContext) at MicroKnights.Logging.AdoNetAppender.InitializeDatabaseConnection()"   for net core 2.0,I think is  the assembly version problem, is there any solution?

**Comment by microknights** [comment]
Is this a runtime exception, or a build/compilation error?

I am using the Log4NetAdoNetAppender nuget in several 2.x .net core projects without troubles

**Comment by gy09535** [comment]
This is runtime exception, I fix this  issue by override ResolveConnectionString method, to use my self config. 
protected override string ResolveConnectionString(out string connectionStringContext)
        {
            connectionStringContext = "ConnectionString";
            return LogOptions.Instance.SqlServerConnString;
        }

**Comment by microknights** [comment]
Seems odd, that you have this error.

Are you running under .Net Standard/Core or .Net Framework?

There is a Nuget package for this library `https://www.nuget.org/packages/MicroKnights.Log4NetAdoNetAppender/`, have you tried that? And another Nuget package for setting the connectionstring manually/runtime `https://www.nuget.org/packages/MicroKnights.Log4NetHelper/`.
