### ISSUE TITLE
cnat't log when website runing a long time

### ISSUE THREAD

**Issue by Meng-Ye** [microknights/Log4NetAdoNetAppender#7]
it wors well when website start 
but zhe next day it can't log to mysql 
when website restart it works again 
my website running in linux .net core 2.2.103

**Comment by microknights** [comment]
Hi @Meng-Ye 

It is a known problem for the AdoNetAppender in general, and not a specific problem for the .Net standard/core version.

First try setting the `reconnectOnError` property to `true` in your configuration - like this:

```
<appender name="AdoNetAppender" type="MicroKnights.Logging.AdoNetAppender, MicroKnights.Log4NetAdoNetAppender">
    <bufferSize value="1" />
    <connectionType value="System.Data.SqlClient.SqlConnection,System.Data,Version=4.0.0.0,Culture=neutral,PublicKeyToken=b77a5c561934e089" />
    <reconnectOnError value="true" />
    <connectionStringName value="log4net" />
    <connectionStringFile value="connectionstrings.json" />
...
```
Secondly there can also be a haxx in the connectionstring by setting `ConnectRetryCount=0`, but i dont know if that works on mysql.

Giv it a try, and report back if the suggestions do not work.

**Comment by Meng-Ye** [comment]
@microknights setting the `reconnectOnError`  property to `true`  in  configuration can solve this problem
thank you very much!
