### ISSUE TITLE
Strong-naming

### ISSUE THREAD

**Issue by jukkahyv** [microknights/Log4NetAdoNetAppender#9]
Would it be possible to add strong name to the assembly on nuget? Unfortunately our project needs strong-named assemblies, and I wouldn't want to disable validation for all assemblies because of this one. Obviously this is something that can be done only by the author who is pushing the assembly to nuget.

**Comment by microknights** [comment]
I am not familiar with strong naming and what side effects that could bring. Also as i read it it is less used, and mostly on the .Net framework platform.

So i think that the solution will be to create a second nuget package that is strong named, with a name like `MicroKnights.Log4NetAdoNetAppender.StrongName` (same way as the Dapper library)

**Comment by jukkahyv** [comment]
As far as I know, the main problem is that adding or removing strong name makes it incompatible with the old assembly, meaning if someone is referencing the assembly without strong name, the assembly with strong name won't be recognized as same. I don't think there's other issues, although of course it makes your publish pipeline a bit more complicated because of the signing step. So yes, adding a separate nuget with strong name is the safest option, and that's also okay for us. Thank you!

**Comment by microknights** [comment]
I have uploaded a nuget `MicroKnights.Log4NetAdoNetAppender.StrongName` including `netstandard2.0` target and with strong naming. It is a prerelease (alpha), so give a status and i will do a full release if it works.

**Comment by mjfiedler** [comment]
@microknights 

1) Thank you very much for putting the effort into this.  Saved my bacon this morning.
2) I also needed strong naming and can confirm that this is working for me.

Please proceed with removing the "alpha" designation.

**Comment by microknights** [comment]
@mjfiedler thanks for verification. The "alpha" will be removed when the #11 fix is verified, since it hits both libraries.

**Comment by microknights** [comment]
@mjfiedler I have made the release now, and closing this issue. If you find anything, create a new issue.
